<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Asso', 'doctrine');

/**
 * BaseAsso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $login
 * @property integer $pole_id
 * @property integer $type_id
 * @property string $url_site
 * @property string $summary
 * @property string $description
 * @property string $logo
 * @property boolean $active
 * @property boolean $passation
 * @property string $salle
 * @property string $phone
 * @property string $facebook
 * @property boolean $joignable
 * @property Pole $Pole
 * @property TypeAsso $Type
 * @property Pole $PoleInfos
 * @property Doctrine_Collection $AssoMember
 * @property Doctrine_Collection $Event
 * @property Doctrine_Collection $Article
 * @property Doctrine_Collection $CharteInfo
 * @property Doctrine_Collection $Materiel
 * @property Doctrine_Collection $Emprunt
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getLogin()       Returns the current record's "login" value
 * @method integer             getPoleId()      Returns the current record's "pole_id" value
 * @method integer             getTypeId()      Returns the current record's "type_id" value
 * @method string              getUrlSite()     Returns the current record's "url_site" value
 * @method string              getSummary()     Returns the current record's "summary" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getLogo()        Returns the current record's "logo" value
 * @method boolean             getActive()      Returns the current record's "active" value
 * @method boolean             getPassation()   Returns the current record's "passation" value
 * @method string              getSalle()       Returns the current record's "salle" value
 * @method string              getPhone()       Returns the current record's "phone" value
 * @method string              getFacebook()    Returns the current record's "facebook" value
 * @method boolean             getJoignable()   Returns the current record's "joignable" value
 * @method Pole                getPole()        Returns the current record's "Pole" value
 * @method TypeAsso            getType()        Returns the current record's "Type" value
 * @method Pole                getPoleInfos()   Returns the current record's "PoleInfos" value
 * @method Doctrine_Collection getAssoMember()  Returns the current record's "AssoMember" collection
 * @method Doctrine_Collection getEvent()       Returns the current record's "Event" collection
 * @method Doctrine_Collection getArticle()     Returns the current record's "Article" collection
 * @method Doctrine_Collection getCharteInfo()  Returns the current record's "CharteInfo" collection
 * @method Doctrine_Collection getMateriel()    Returns the current record's "Materiel" collection
 * @method Doctrine_Collection getEmprunt()     Returns the current record's "Emprunt" collection
 * @method Asso                setName()        Sets the current record's "name" value
 * @method Asso                setLogin()       Sets the current record's "login" value
 * @method Asso                setPoleId()      Sets the current record's "pole_id" value
 * @method Asso                setTypeId()      Sets the current record's "type_id" value
 * @method Asso                setUrlSite()     Sets the current record's "url_site" value
 * @method Asso                setSummary()     Sets the current record's "summary" value
 * @method Asso                setDescription() Sets the current record's "description" value
 * @method Asso                setLogo()        Sets the current record's "logo" value
 * @method Asso                setActive()      Sets the current record's "active" value
 * @method Asso                setPassation()   Sets the current record's "passation" value
 * @method Asso                setSalle()       Sets the current record's "salle" value
 * @method Asso                setPhone()       Sets the current record's "phone" value
 * @method Asso                setFacebook()    Sets the current record's "facebook" value
 * @method Asso                setJoignable()   Sets the current record's "joignable" value
 * @method Asso                setPole()        Sets the current record's "Pole" value
 * @method Asso                setType()        Sets the current record's "Type" value
 * @method Asso                setPoleInfos()   Sets the current record's "PoleInfos" value
 * @method Asso                setAssoMember()  Sets the current record's "AssoMember" collection
 * @method Asso                setEvent()       Sets the current record's "Event" collection
 * @method Asso                setArticle()     Sets the current record's "Article" collection
 * @method Asso                setCharteInfo()  Sets the current record's "CharteInfo" collection
 * @method Asso                setMateriel()    Sets the current record's "Materiel" collection
 * @method Asso                setEmprunt()     Sets the current record's "Emprunt" collection
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asso');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('login', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('pole_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('url_site', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('summary', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('logo', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('passation', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('salle', 'string', 6, array(
             'type' => 'string',
             'length' => 6,
             ));
        $this->hasColumn('phone', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('facebook', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('joignable', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pole', array(
             'local' => 'pole_id',
             'foreign' => 'id'));

        $this->hasOne('TypeAsso as Type', array(
             'local' => 'type_id',
             'foreign' => 'id'));

        $this->hasOne('Pole as PoleInfos', array(
             'local' => 'id',
             'foreign' => 'asso_id'));

        $this->hasMany('AssoMember', array(
             'local' => 'id',
             'foreign' => 'asso_id'));

        $this->hasMany('Event', array(
             'local' => 'id',
             'foreign' => 'asso_id'));

        $this->hasMany('Article', array(
             'local' => 'id',
             'foreign' => 'asso_id'));

        $this->hasMany('CharteInfo', array(
             'local' => 'id',
             'foreign' => 'asso_id'));

        $this->hasMany('Materiel', array(
             'local' => 'id',
             'foreign' => 'asso_id'));

        $this->hasMany('Emprunt', array(
             'local' => 'id',
             'foreign' => 'asso_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}