<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserSemestre', 'doctrine');

/**
 * BaseUserSemestre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $branche_id
 * @property string $num
 * @property string $abroad
 * @property integer $semestre_id
 * @property Profile $Profile
 * @property Branche $Branche
 * @property Semestre $Semestre
 * @property Doctrine_Collection $UserUv
 * 
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method integer             getBrancheId()   Returns the current record's "branche_id" value
 * @method string              getNum()         Returns the current record's "num" value
 * @method string              getAbroad()      Returns the current record's "abroad" value
 * @method integer             getSemestreId()  Returns the current record's "semestre_id" value
 * @method Profile             getProfile()     Returns the current record's "Profile" value
 * @method Branche             getBranche()     Returns the current record's "Branche" value
 * @method Semestre            getSemestre()    Returns the current record's "Semestre" value
 * @method Doctrine_Collection getUserUv()      Returns the current record's "UserUv" collection
 * @method UserSemestre        setUserId()      Sets the current record's "user_id" value
 * @method UserSemestre        setBrancheId()   Sets the current record's "branche_id" value
 * @method UserSemestre        setNum()         Sets the current record's "num" value
 * @method UserSemestre        setAbroad()      Sets the current record's "abroad" value
 * @method UserSemestre        setSemestreId()  Sets the current record's "semestre_id" value
 * @method UserSemestre        setProfile()     Sets the current record's "Profile" value
 * @method UserSemestre        setBranche()     Sets the current record's "Branche" value
 * @method UserSemestre        setSemestre()    Sets the current record's "Semestre" value
 * @method UserSemestre        setUserUv()      Sets the current record's "UserUv" collection
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserSemestre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_semestre');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('branche_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('num', 'string', 4, array(
             'type' => 'string',
             'length' => 4,
             ));
        $this->hasColumn('abroad', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('semestre_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Branche', array(
             'local' => 'branche_id',
             'foreign' => 'id'));

        $this->hasOne('Semestre', array(
             'local' => 'semestre_id',
             'foreign' => 'id'));

        $this->hasMany('UserUv', array(
             'local' => 'id',
             'foreign' => 'user_semestre_id'));
    }
}