<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserSport', 'doctrine');

/**
 * BaseUserSport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $sport_id
 * @property Profile $Profile
 * @property Sport $Sport
 * 
 * @method integer   getUserId()   Returns the current record's "user_id" value
 * @method integer   getSportId()  Returns the current record's "sport_id" value
 * @method Profile   getProfile()  Returns the current record's "Profile" value
 * @method Sport     getSport()    Returns the current record's "Sport" value
 * @method UserSport setUserId()   Sets the current record's "user_id" value
 * @method UserSport setSportId()  Sets the current record's "sport_id" value
 * @method UserSport setProfile()  Sets the current record's "Profile" value
 * @method UserSport setSport()    Sets the current record's "Sport" value
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserSport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_sport');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sport_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Sport', array(
             'local' => 'sport_id',
             'foreign' => 'id'));
    }
}