<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserUv', 'doctrine');

/**
 * BaseUserUv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uv_id
 * @property integer $user_semestre_id
 * @property string $note
 * @property Uv $Uv
 * @property UserSemestre $UserSemestre
 * 
 * @method integer      getUvId()             Returns the current record's "uv_id" value
 * @method integer      getUserSemestreId()   Returns the current record's "user_semestre_id" value
 * @method string       getNote()             Returns the current record's "note" value
 * @method Uv           getUv()               Returns the current record's "Uv" value
 * @method UserSemestre getUserSemestre()     Returns the current record's "UserSemestre" value
 * @method UserUv       setUvId()             Sets the current record's "uv_id" value
 * @method UserUv       setUserSemestreId()   Sets the current record's "user_semestre_id" value
 * @method UserUv       setNote()             Sets the current record's "note" value
 * @method UserUv       setUv()               Sets the current record's "Uv" value
 * @method UserUv       setUserSemestre()     Sets the current record's "UserSemestre" value
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserUv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_uv');
        $this->hasColumn('uv_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_semestre_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('note', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Uv', array(
             'local' => 'uv_id',
             'foreign' => 'id'));

        $this->hasOne('UserSemestre', array(
             'local' => 'user_semestre_id',
             'foreign' => 'id'));
    }
}