<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Semestre', 'doctrine');

/**
 * BaseSemestre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $AssoMember
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getAssoMember() Returns the current record's "AssoMember" collection
 * @method Semestre            setName()       Sets the current record's "name" value
 * @method Semestre            setAssoMember() Sets the current record's "AssoMember" collection
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSemestre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('semestre');
        $this->hasColumn('name', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AssoMember', array(
             'local' => 'id',
             'foreign' => 'semestre_id'));
    }
}