<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CharteInfo', 'doctrine');

/**
 * BaseCharteInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $date
 * @property integer $semestre_id
 * @property integer $asso_id
 * @property integer $responsable_id
 * @property boolean $confirmation
 * @property Semestre $Semestre
 * @property Asso $Asso
 * @property sfGuardUser $Responsable
 * 
 * @method date        getDate()           Returns the current record's "date" value
 * @method integer     getSemestreId()     Returns the current record's "semestre_id" value
 * @method integer     getAssoId()         Returns the current record's "asso_id" value
 * @method integer     getResponsableId()  Returns the current record's "responsable_id" value
 * @method boolean     getConfirmation()   Returns the current record's "confirmation" value
 * @method Semestre    getSemestre()       Returns the current record's "Semestre" value
 * @method Asso        getAsso()           Returns the current record's "Asso" value
 * @method sfGuardUser getResponsable()    Returns the current record's "Responsable" value
 * @method CharteInfo  setDate()           Sets the current record's "date" value
 * @method CharteInfo  setSemestreId()     Sets the current record's "semestre_id" value
 * @method CharteInfo  setAssoId()         Sets the current record's "asso_id" value
 * @method CharteInfo  setResponsableId()  Sets the current record's "responsable_id" value
 * @method CharteInfo  setConfirmation()   Sets the current record's "confirmation" value
 * @method CharteInfo  setSemestre()       Sets the current record's "Semestre" value
 * @method CharteInfo  setAsso()           Sets the current record's "Asso" value
 * @method CharteInfo  setResponsable()    Sets the current record's "Responsable" value
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCharteInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('charte_info');
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('semestre_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('asso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('responsable_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('confirmation', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Semestre', array(
             'local' => 'semestre_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Asso', array(
             'local' => 'asso_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Responsable', array(
             'local' => 'responsable_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}