<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Role', 'doctrine');

/**
 * BaseRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $order
 * @property Doctrine_Collection $AssoMember
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getOrder()      Returns the current record's "order" value
 * @method Doctrine_Collection getAssoMember() Returns the current record's "AssoMember" collection
 * @method Role                setName()       Sets the current record's "name" value
 * @method Role                setOrder()      Sets the current record's "order" value
 * @method Role                setAssoMember() Sets the current record's "AssoMember" collection
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('role');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('order', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AssoMember', array(
             'local' => 'id',
             'foreign' => 'role'));
    }
}