<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Abonnement', 'doctrine');

/**
 * BaseAbonnement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $asso_id
 * @property integer $type_publication
 * @property Asso $Asso
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()           Returns the current record's "user_id" value
 * @method integer     getAssoId()           Returns the current record's "asso_id" value
 * @method integer     getTypePublication()  Returns the current record's "type_publication" value
 * @method Asso        getAsso()             Returns the current record's "Asso" value
 * @method sfGuardUser getUser()             Returns the current record's "User" value
 * @method Abonnement  setUserId()           Sets the current record's "user_id" value
 * @method Abonnement  setAssoId()           Sets the current record's "asso_id" value
 * @method Abonnement  setTypePublication()  Sets the current record's "type_publication" value
 * @method Abonnement  setAsso()             Sets the current record's "Asso" value
 * @method Abonnement  setUser()             Sets the current record's "User" value
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAbonnement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('abonnement');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('asso_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type_publication', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Asso', array(
             'local' => 'asso_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}