<?php

/**
 * BaseEmprunt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $materiel_id
 * @property integer $user_id
 * @property integer $asso_id
 * @property integer $nombre
 * @property boolean $recu
 * @property boolean $rendu
 * @property Materiel $Materiel
 * @property sfGuardUser $User
 * @property Asso $Asso
 * 
 * @method integer     getMaterielId()  Returns the current record's "materiel_id" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method integer     getAssoId()      Returns the current record's "asso_id" value
 * @method integer     getNombre()      Returns the current record's "nombre" value
 * @method boolean     getRecu()        Returns the current record's "recu" value
 * @method boolean     getRendu()       Returns the current record's "rendu" value
 * @method Materiel    getMateriel()    Returns the current record's "Materiel" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method Asso        getAsso()        Returns the current record's "Asso" value
 * @method Emprunt     setMaterielId()  Sets the current record's "materiel_id" value
 * @method Emprunt     setUserId()      Sets the current record's "user_id" value
 * @method Emprunt     setAssoId()      Sets the current record's "asso_id" value
 * @method Emprunt     setNombre()      Sets the current record's "nombre" value
 * @method Emprunt     setRecu()        Sets the current record's "recu" value
 * @method Emprunt     setRendu()       Sets the current record's "rendu" value
 * @method Emprunt     setMateriel()    Sets the current record's "Materiel" value
 * @method Emprunt     setUser()        Sets the current record's "User" value
 * @method Emprunt     setAsso()        Sets the current record's "Asso" value
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmprunt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emprunt');
        $this->hasColumn('materiel_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('asso_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nombre', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('recu', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('rendu', 'boolean', null, array(
             'type' => 'boolean',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Materiel', array(
             'local' => 'materiel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Asso', array(
             'local' => 'asso_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}