<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pole', 'doctrine');

/**
 * BasePole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $asso_id
 * @property string $couleur
 * @property Asso $Infos
 * @property Doctrine_Collection $Asso
 * 
 * @method integer             getAssoId()  Returns the current record's "asso_id" value
 * @method string              getCouleur() Returns the current record's "couleur" value
 * @method Asso                getInfos()   Returns the current record's "Infos" value
 * @method Doctrine_Collection getAsso()    Returns the current record's "Asso" collection
 * @method Pole                setAssoId()  Sets the current record's "asso_id" value
 * @method Pole                setCouleur() Sets the current record's "couleur" value
 * @method Pole                setInfos()   Sets the current record's "Infos" value
 * @method Pole                setAsso()    Sets the current record's "Asso" collection
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pole');
        $this->hasColumn('asso_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('couleur', 'string', 7, array(
             'type' => 'string',
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Asso as Infos', array(
             'local' => 'asso_id',
             'foreign' => 'id'));

        $this->hasMany('Asso', array(
             'local' => 'id',
             'foreign' => 'pole_id'));
    }
}