<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Article', 'doctrine');

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $asso_id
 * @property string $name
 * @property string $text
 * @property boolean $is_weekmail
 * @property string $image
 * @property string $summary
 * @property Asso $Asso
 * 
 * @method integer getAssoId()      Returns the current record's "asso_id" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getText()        Returns the current record's "text" value
 * @method boolean getIsWeekmail()  Returns the current record's "is_weekmail" value
 * @method string  getImage()       Returns the current record's "image" value
 * @method string  getSummary()     Returns the current record's "summary" value
 * @method Asso    getAsso()        Returns the current record's "Asso" value
 * @method Article setAssoId()      Sets the current record's "asso_id" value
 * @method Article setName()        Sets the current record's "name" value
 * @method Article setText()        Sets the current record's "text" value
 * @method Article setIsWeekmail()  Sets the current record's "is_weekmail" value
 * @method Article setImage()       Sets the current record's "image" value
 * @method Article setSummary()     Sets the current record's "summary" value
 * @method Article setAsso()        Sets the current record's "Asso" value
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('asso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('is_weekmail', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('image', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('summary', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Asso', array(
             'local' => 'asso_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}