<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Image', 'doctrine');

/**
 * BaseImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $legend
 * @property integer $album_id
 * @property Album $Album
 * 
 * @method string  getName()     Returns the current record's "name" value
 * @method string  getLegend()   Returns the current record's "legend" value
 * @method integer getAlbumId()  Returns the current record's "album_id" value
 * @method Album   getAlbum()    Returns the current record's "Album" value
 * @method Image   setName()     Sets the current record's "name" value
 * @method Image   setLegend()   Sets the current record's "legend" value
 * @method Image   setAlbumId()  Sets the current record's "album_id" value
 * @method Image   setAlbum()    Sets the current record's "Album" value
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('legend', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('album_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Album', array(
             'local' => 'album_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}