<?php

/**
 * BaseMateriel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property integer $asso_id
 * @property string $description
 * @property Asso $Asso
 * @property Doctrine_Collection $Stock
 * @property Doctrine_Collection $Emprunt
 * 
 * @method string              getNom()         Returns the current record's "nom" value
 * @method integer             getAssoId()      Returns the current record's "asso_id" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Asso                getAsso()        Returns the current record's "Asso" value
 * @method Doctrine_Collection getStock()       Returns the current record's "Stock" collection
 * @method Doctrine_Collection getEmprunt()     Returns the current record's "Emprunt" collection
 * @method Materiel            setNom()         Sets the current record's "nom" value
 * @method Materiel            setAssoId()      Sets the current record's "asso_id" value
 * @method Materiel            setDescription() Sets the current record's "description" value
 * @method Materiel            setAsso()        Sets the current record's "Asso" value
 * @method Materiel            setStock()       Sets the current record's "Stock" collection
 * @method Materiel            setEmprunt()     Sets the current record's "Emprunt" collection
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMateriel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('materiel');
        $this->hasColumn('nom', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('asso_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Asso', array(
             'local' => 'asso_id',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Stock', array(
             'local' => 'id',
             'foreign' => 'materiel_id'));

        $this->hasMany('Emprunt', array(
             'local' => 'id',
             'foreign' => 'materiel_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}