<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EventType', 'doctrine');

/**
 * BaseEventType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $color
 * @property Doctrine_Collection $Event
 * 
 * @method string              getName()  Returns the current record's "name" value
 * @method string              getColor() Returns the current record's "color" value
 * @method Doctrine_Collection getEvent() Returns the current record's "Event" collection
 * @method EventType           setName()  Sets the current record's "name" value
 * @method EventType           setColor() Sets the current record's "color" value
 * @method EventType           setEvent() Sets the current record's "Event" collection
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_type');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('color', 'string', 7, array(
             'type' => 'string',
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Event', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}