<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Filiere', 'doctrine');

/**
 * BaseFiliere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Profile
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getProfile() Returns the current record's "Profile" collection
 * @method Filiere             setName()    Sets the current record's "name" value
 * @method Filiere             setProfile() Sets the current record's "Profile" collection
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFiliere extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('filiere');
        $this->hasColumn('name', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Profile', array(
             'local' => 'id',
             'foreign' => 'filiere_id'));
    }
}