<?php

/**
 * AdressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdressTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Adress');
    }
}