<?php

/**
 * AlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Album');
    }
    
      public function getImages($album = null) {
          
     if(!is_null($album))
    $q = $this->createQuery('a')
            ->select('a.*')
            ->where('album_id = ?'. $album->getPrimaryKey());
    

    return $q;
  }
  
  
}