<?php

/**
 * AnnonceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnnonceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnnonceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Annonce');
    }
}