<?php

/**
 * AnnoncesCategorieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnnoncesCategorieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnnoncesCategorieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnnoncesCategorie');
    }
}