<?php

/**
 * AssoMemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssoMemberTable extends Doctrine_Table
{

  /**
   * Recharge les permissions de l'utilisateur courant après une modification de la table
   * 
   * @param sfEvent $event 
   */
  public function postSave($event)
  {
    parent::postSave($event);
    $this->getUser()->reloadGroupsAndPermissions();
  }

  /**
   * Returns an instance of this class.
   *
   * @return object AssoMemberTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('AssoMember');
  }

  public function getBureau($asso)
  {
    $q = $this->createQuery('q')
      ->where('asso_id = ?',$asso->getId())
      ->leftJoin('q.Role r')
      ->leftJoin('q.User u')
      ->leftJoin('u.Profile p')
      ->leftJoin('q.Semestre s')
      ->andWhere('r.bureau = 1');

    return $q->execute();
  }
  
  public function getMembres($asso)
  {
    $q = $this->createQuery('q')
      ->where('asso_id = ?',$asso->getId())
      ->leftJoin('q.Role r')
      ->leftJoin('q.User u')
      ->leftJoin('u.Profile p')
      ->leftJoin('q.Semestre s');

    return $q->execute();
  }

}