<?php

/**
 * AssoMemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssoMemberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssoMemberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssoMember');
    }
}