<?php

/**
 * AvanceTresoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvanceTresoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvanceTresoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AvanceTreso');
    }

    public function getAllforEmetteur($asso)
    {
        $q = $this->createQuery('q')->where('q.emetteur_id = ?', $asso->getPrimaryKey());
        return $q;
    }
}