<?php

/**
 * BrancheTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BrancheTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BrancheTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Branche');
    }
}