<?php

/**
 * Budget
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Budget extends BaseBudget {

    public function getCategories() {
        return BudgetCategorieTable::getInstance()->getCategoriesForBudget($this)->andWhere('BudgetCategorie.deleted_at is NULL');
    }

    public function getCategoriesWithEntry(){
        $q = $this->getCategories()
        ->leftJoin('BudgetPoste b')
        ->andwhere('b.budget_categorie_id = q.id')
        ->andWhere('b.id IS NOT NULL');
        return $q;
    }

    public function getCategoriesWithoutEntry(){
        $q = BudgetCategorieTable::getInstance()->getActiveCategories($this->getAssoId())
        ->andWhere('(SELECT COUNT(*) FROM BudgetPoste b WHERE b.budget_categorie_id = q.id) = 0');
        return $q;
    }

}
