<?php

/**
 * BudgetCategorieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BudgetCategorieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BudgetCategorieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BudgetCategorie');
    }
}