<?php

/**
 * BudgetPosteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BudgetPosteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BudgetPosteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BudgetPoste');
    }
}