<?php

/**
 * BudgetMoyenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BudgetMoyenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BudgetMoyenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BudgetMoyen');
    }
}