<?php

/**
 * CarnetAvantagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarnetAvantagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CarnetAvantagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CarnetAvantages');
    }
    
    public function getCarnetAvantagesList() {
        $q = $this->createQuery('a')
            ->select('a.*');
        return $q;
    }
}
