<?php

/**
 * CharteInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CharteInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CharteInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CharteInfo');
    }
    
    public function getByAssoAndSemestre($asso_id,$semestre_id = NULL)
    {
      if(!$semestre_id)
        $semestre_id = sfConfig::get('app_portail_current_semestre');
      $q = $this->createQuery('q')
          ->where('q.asso_id = ?',$asso_id)
          ->andWhere('q.semestre_id = ?', $semestre_id);
      return $q;
    }
}