<?php

/**
 * CharteLocaux
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CharteLocaux extends BaseCharteLocaux
{
  public function getStatutString()
  {
    switch ($this->getStatut())
    {
      case 0: return "Charte non signée par l'étudiant"; break;

      case 1: return "Charte signée par l'étudiant"; break;

      case 2: return "Charte validée par le président"; break;

      case 3: return "Charte validée"; break;

      default: return "Charte invalide"; break;
    }
  }

  public function getAccesLocaux()
  {
    $res="";
    if ($this->getPorteMde()==1) $res.="Porte de la MDE / ";
    if ($this->getBatA()==1) $res.="Batiment A / ";
    if ($this->getMdeComplete()==1) $res.=" MDE complète / ";
    if ($this->getLocauxPic()==1) $res.="Locaux du PIC / ";
    if ($this->getBureauPolar()==1) $res.="Bureau du Polar / ";
    if ($this->getPermPolar()==1) $res.="Permanence du Polar / ";
    if ($this->getSallesMusique()==1) $res.="Salles de musique / ";
    $res = substr($res, 0, -3);
    return $res;
  }
}
