<?php

/**
 * CharteLocauxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CharteLocauxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CharteLocauxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CharteLocaux');
    }
}