<?php

/**
 * CompteBanquaireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompteBanquaireTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompteBanquaireTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompteBanquaire');
    }
    
    public function getAllForAsso($asso) {
        $q = $this->createQuery('q')
                  ->where('q.asso_id = ?', $asso->getPrimaryKey())
                  ->andWhere('q.deleted_at IS NULL');
        return $q;
    }
}