<?php

/**
 * CompteBanquaireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompteBanquaireTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompteBanquaireTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompteBanquaire');
    }
}