<?php

/**
 * DocumentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocumentType');
    }
}