<?php

/**
 * Document
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Document extends BaseDocument
{
    public function __toString()
    {
        return $this->getNom();
    }

    public function getPath() {
        return sfConfig::get('app_portail_dossier_assos') . '/' . $this->getAsso()->getLogin() . '/documents/' . $this->getDocumentType()->getSlug() . '/' . $this->getFichier();
    }

    public function deleteAndUnlink() {
        unlink($this->getPath);
        $this->delete();
    }

    public function generatePDF($title = 'BDE-UTC: Outil de trésorerie', $nom, $html, $culture = 'fr') {
        $this->fichier = $nom . '.pdf';
        $pdf = new Pdf($this->getAsso(), $title);
        return $pdf->generate($this->getDocumentType()->getSlug(), $html, $nom);
    }

    public function setTypeFromSlug($slug) {
        $this->setDocumentType(DocumentTypeTable::getInstance()->findOneBySlug($slug));
    }
}
