<?php

/**
 * DocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Document');
    }

    public function getAllForAsso($asso)
    {
        $q = DocumentTable::getInstance()->createQuery('q')
            ->where('q.asso_id = ?', $asso->getPrimaryKey())
            ->orderBy('q.created_at DESC');
        return $q;
    }

    public function getAllForTransaction($transaction)
    {
        $q = DocumentTable::getInstance()->createQuery('q')
            ->where('q.transaction_id = ?', $transaction->getPrimaryKey());
        return $q;
    }
}