<?php

/**
 * EmpruntTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpruntTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object EmpruntTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Emprunt');
  }

  public function getAllByAsso($asso)
  {
    $q = $this->createQuery('q')
            ->where('q.asso_id = ?', $asso->getId())
            ->andWhere('q.rendu = ?', false);
    return $q;
  }

}