<?php

/**
 * EtatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EtatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EtatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Etat');
    }
}