<?php

/**
 * EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Event');
    }
    
  /**
   * 
   * Fetch the list of all events sorted by date.
   * 
   * @param int $asso_id
   */
  public function getEventsList($asso_id = null)
  {
    $q = $this->createQuery('a')
      ->addOrderBy('a.created_at DESC');

    if(!is_null($asso_id))
      $q = $q->where("a.asso_id = ?",$asso_id);

    return $q->execute();
  }

  /**
   * 
   * Fetch the list of all events in future.
   *  
   */
  public function getFutureEventsList()
  {
    $q = $this->createQuery('a')
      ->addOrderBy('a.created_at DESC');
    $q = $q->where("a.start_date > ?","NOW");

    return $q->execute();
  }
}
