<?php

/**
 * EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Event');
    }
    
  /**
   * 
   * Fetch the list of all events sorted by date.
   * 
   * @param int $asso_id
   */
  public function getEventsList($asso = null)
  {
    $q = $this->createQuery('a')
      ->select('a.*')
      ->addOrderBy('a.created_at DESC');

    /*if(!is_null($asso))
      if($asso->isPole())
        $q = $q->leftJoin('Asso as')->where("as.pole_id = ?",$asso->getPrimaryKey());
      else*/
        $q = $q->where("a.asso_id = ?",$asso->getPrimaryKey());

    return $q;
  }

  /**
   * 
   * Fetch the list of all events in future.
   *  
   */
  public function getFutureEventsList()
  {
    $q = $this->createQuery('a')
      ->addOrderBy('a.start_date ASC');
    $q = $q->where("a.start_date > NOW()");

    return $q;
  }

  public function getLastEvents($count = 3)
  {
    $q = $this->getFutureEventsList()
      ->limit($count);
    return $q;
  }
}
