<?php

/**
 * EventGuestAssoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventGuestAssoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventGuestAssoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventGuestAsso');
    }
}