<?php

/**
 * GaleriePhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GaleriePhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GaleriePhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GaleriePhoto');
    }

    public function getEvent($event_id){
    	$q = $this->createQuery('g')
    		->select('g.*, e.*')
    		->leftJoin('g.Event e')
    		->where('e.id = ?', $event_id);

    	return $q;
    }
}