<?php

/**
 * GaleriePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GaleriePhoto extends BaseGaleriePhoto
{
	public function delete(Doctrine_Connection $conn = NULL){
		PhotoTable::getInstance()->deletePhotosFromGallery($this->getId());
		parent::delete($conn);
	}

	public function userIsPhotographer($user){
    	return $this->getEvent()->userIsPhotographer($user);
  	}

  	public function countPhotosVisible($logged_in=False){
  		return PhotoTable::getInstance()
	        ->getPhotos($this->getId(),$logged_in)
	        ->count();
  	}  
}
