<?php

/**
 * InfoJobSignalementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfoJobSignalementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfoJobSignalementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InfoJobSignalement');
    }
}