<?php

/**
 * InfoJobSignalementTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfoJobSignalementTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfoJobSignalementTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InfoJobSignalementType');
    }
}