<?php

/**
 * InfoJobOffreDisponibiliteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfoJobOffreDisponibiliteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfoJobOffreDisponibiliteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InfoJobOffreDisponibilite');
    }
}