<?php

/**
 * InfoJobOffre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class InfoJobOffre extends BaseInfoJobOffre
{
  public function activate() {
    if($this->getValidationDate() != NULL)
      return false;
    $this->setDateTimeObject('validation_date', new DateTime());
    $this->save();
    return true;
  }

  public function archive() {
    if($this->getArchivageDate() != NULL)
      return false;
    $this->setDateTimeObject('archivage_date', new DateTime());
    $this->save();
    return true;
  }
}
