<?php

/**
 * InfoJobCategorieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfoJobCategorieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfoJobCategorieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InfoJobCategorie');
    }
}