<?php

/**
 * InfoJobAbonnementDisponibiliteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfoJobAbonnementDisponibiliteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfoJobAbonnementDisponibiliteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InfoJobAbonnementDisponibilite');
    }
}