<?php

/**
 * InfoJobDisponibiliteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfoJobDisponibiliteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfoJobDisponibiliteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InfoJobDisponibilite');
    }
}