<?php

/**
 * InfoJobAbonnementCategorieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfoJobAbonnementCategorieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfoJobAbonnementCategorieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InfoJobAbonnementCategorie');
    }
}