<?php

/**
 * MaterielTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterielTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterielTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Materiel');
    }
    
    public function getAllByAsso($asso)
    {
      $q = $this->createQuery('q')
          ->where('q.asso_id = ?',$asso->getId());
      return $q;
    }
}