<?php

/**
 * MembreServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MembreServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MembreServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MembreService');
    }
    
    public function getServicesFavoris($user_id){
      $q = $this->createQuery('ar')
            ->select ('se.nom, se.url, ar.*')
            ->where('ar.membre = ?', $user_id)
            ->andWhere('ar.service = se.id')
            ->leftJoin('ar.Service se')
            ->orderBy('ar.updated_at desc');
      return $q;
    }
    

    public function getCurrentServiceFollower($service, $user) {
      $q = $this->createQuery('q')
            ->where('q.service = ?', $service)
            ->andWhere('q.membre = ?', $user);
      return $q;
    } 
  
}
