<?php

/**
 * MembresServicesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MembresServicesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MembresServicesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MembresServices');
    }
    
    public function getServicesFavoris($user_id){
      $q = $this->createQuery('ar')
            ->select ('se.nom, se.url, ar.*')
            ->where('ar.membre = ?', $user_id)
            ->andWhere('ar.service = se.id')
            ->leftJoin('ar.Services se')
            ->orderBy('ar.updated_at desc')
            ->limit(5);            
      return $q;
    }
}
