<?php

/**
 * NoteDeFrais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NoteDeFrais extends BaseNoteDeFrais
{
    public function addAchatFromId($achat) {
        $transaction = TransactionTable::getInstance()->find($achat);
        if ($transaction == false)
            return false;
        $this->addAchat($transaction);
        return $transaction;
    }

    public function addAchat(Transaction $transaction) {
        $transaction->setNoteDeFrais($this);
        $transaction->save();
        $this->getTransaction()->montant += $transaction->getMontant();
    }
}
