<?php

/**
 * PartenaireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PartenaireTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PartenaireTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Partenaire');
    }
}