<?php

/**
 * Photo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Photo extends BasePhoto
{
	public function getPass(){
		return substr($this->getImage(), 0, 8);	
	}
 	public function userIsPhotographer($user){
      
      return $user->isAuthenticated() && (
        $user->getGuardUser()->getId()==$this->getAuthor() ||
        $this->getGaleriePhoto()->userIsPhotographer($user));
  
  	}

	public function getExifs(){
		return exif_read_data(sfConfig::get('sf_root_dir')."/web/uploads/galeries/source/".
            $this->getImage());
	}
	
}
