<?php

/**
 * PoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PoleTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object PoleTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Pole');
  }
  
  public function getAllWithInfos()
  {
    $q = $this->createQuery('q')
      ->leftJoin('q.Infos i');
    
    return $q;
  }

}
