<?php

/**
 * PoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PoleTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object PoleTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Pole');
  }

  public function getPolesList()
  {
  $q = $this->createQuery('p')
    ->addOrderBy('p.id ASC');

  return $q;
  }
  
  public function getAllWithInfos()
  {
    $q = $this->createQuery('q')
      ->leftJoin('q.Infos i');
    
    return $q;
  }

  public function getOneByAsso($asso)
  {
    $q = $this->createQuery('p')
      ->where('p.asso_id = ?', $asso->getPrimaryKey());
    return $q->fetchOne();
  }

  public function getOneById($id)
  {
    $q = $this->createQuery('p')
      ->where('p.id = ?', $id);
    return $q->fetchOne();
  }
  
  /* Statistiques Reservations Poles */
    public function getStatPole()
    {
  $q = $this->createQuery('p')
            ->select('p.*, a.*, r.*, count(r.id) as count_resa')
      ->leftJoin('p.Asso a')
            ->leftJoin('a.Reservation r')
      ->groupBy('p.id')
            ->addOrderBy('p.id ASC');

  return $q;
    }

}
