<?php

/**
 * Reservation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Reservation extends BaseReservation
{
/*
	public function __toString()
	{

	}
*/

	public function getUserValid()
	{
		return sfGuardUserTable::getInstance()->getUserById($this->getIdUserValid())->execute()[0];
	}
	
	public function getUserReserve()
	{
		return sfGuardUserTable::getInstance()->getUserById($this->getIdUserReserve())->execute()[0];
	}

}
