<?php

/**
 * ReservationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReservationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReservationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reservation');
    }
    
    public function getAllReservation()
    {
      	$q = $this->createQuery('q');
            
         return $q;
    }
    
    public function getReservationBySalle($salle)
    {
        $q = $this->createQuery('a')
            ->select('a.*, as.id, as.name as Name, p.couleur')
            ->leftJoin('a.Asso as')
	    ->where("a.id_salle = ?", $salle)
            ->addOrderBy('a.date');
            
         return $q;
    }

  /*public function getAsso($idAsso)
  {
    $q = $this->createQuery('q')
	    ->where('q.asso_id = ?', $idAsso);
    
	return $q;
  }*/




}
