<?php

/**
 * ReservationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReservationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReservationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reservation');
    }
    
    public function getAllReservation()
    {
      	$q = $this->createQuery('q');
            
         return $q;
    }
    
    public function getReservationById($id)
    {
		
        $q = $this->createQuery('q')
	    		->where('q.id = ?', $id)
            ->addOrderBy('date');
        	
         return $q;
    }
    
    public function getReservationBySalle($salle)
    {
        $q = $this->createQuery('a')
	    ->where('a.id_salle = ?', $salle)
            ->addOrderBy('a.date');
            
         return $q;
    }
    
    public function isReservationExist($id)
    {
    		$q = $this->createQuery()
	    		->where('id = ?', $id)->execute();
            
         return (count($q) > 0);
    }
    
    public function isReservationNoValidExist($id)
    {
    		$q = $this->createQuery()
	    		->where('id = ?', $id)
            ->andWhere('estValide=?', 0)->execute();
            
         return (count($q) > 0);
    }
  
  public function getReservationNoValide()
  {
  		$q = $this->createQuery('a')
  				->where('a.estValide=?', 0)
  				->addOrderBy('a.date','ASC');
  				
  		return $q;
  }

	public function getReservationByPole($pole)
	{
		$q = $this->createQuery('a')
				->leftJoin('a.Salle s')
				->leftJoin('s.Pole p')
				->where('p.id=?',$pole)
				->addOrderBy('a.date','ASC');
			
		return $q;	
	}


	public function getStatJours()
	{
		$q = Doctrine_Manager::getInstance()->getCurrentConnection();
		$result = $q->execute("select r.*, count(r.id) as count_resa, weekday(r.date) as dow from reservation r group by dow order by dow");

		return $result;
	}

	public function getStatMois()
	{
		$q = Doctrine_Manager::getInstance()->getCurrentConnection();
		$result = $q->execute("select r.*, count(r.id) as count_resa, month(r.date) as month from reservation r group by month order by month");

		return $result;
	}
}
