<?php

/**
 * SalleCreneauOffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalleCreneauOffTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalleCreneauOffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SalleCreneauOff');
    }
}