<?php

/**
 * SalleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Salle');
    }
    
    public function getAllSalles()
    {
     		return $this->createQuery();
    }
    
    public function getSalleById($id)
    {
    		$q = $this->createQuery('q')->where('q.id=?',$id)->limit(1);
    		
    		return $q;
    }
    
    public function deleteSalle($id)
    {
    		$q = $this->createQuery()
    					->delete()
    					->where('id=?',$id);
    		
    		return $q;
    }
    
    public function isSalleExist($id)
    {
    		$salle = $this->getSalleById($id)->execute();
    		
    		return (count($salle) > 0);
    }
    
    public function getSalleByPole()
    {
    		$q = $this->createQuery('q')
    					->leftJoin('q.Pole p')
    					->leftJoin('p.Asso a')
    					->orderBy('p.asso_id');
    					
    		//$a = $q->execute();
    		
    		return $q;
    }
    
}
