<?php

/**
 * SemestreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SemestreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SemestreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Semestre');
    }
}