<?php

/**
 * ServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Service');
    }
    
    public function getServicesList(){
       $q = $this->createQuery('a')
            ->select('a.*')
            ->leftJoin('a.Type s');
            return $q;
    }
}
