<?php

/**
 * ServicesTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicesTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicesTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServicesType');
    }
}