<?php

/**
 * Service
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Service extends BaseService {
    public function addFollower(sfGuardUser $user, Service $service) {
        $serviceFollower = new MembreService();
        $serviceFollower->setService($service);
        $serviceFollower->setMembre($user);
        $serviceFollower->save();
    }

    public function removeFollower(sfGuardUser $user, Service $service) {
        $assoFollower = MembreServiceTable::getInstance()->getCurrentServiceFollower($service->getPrimaryKey(), $user->getPrimaryKey())->fetchOne();
        $assoFollower->delete();
    }
}
