<?php

/**
 * SportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sport');
    }
}