<?php

/**
 * StockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StockTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object StockTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Stock');
  }

  public function getAllWhereDisponible()
  {
    $q = $this->getAll()->where('q.etat_id = ?', 1);

    return $q;
  }

  public function getAllWhereEmprunte()
  {
    $q = $this->getAll()->where('q.etat_id = ?', 2);

    return $q;
  }

  public function getAllWherePerdu()
  {
    $q = $this->getAll()->where('q.etat_id = ?', 3);

    return $q;
  }

  public function getDispoForMateriel($materiel_id)
  {
    $q = $this->createQuery('s')
        ->select('SUM(s.nombre) as stock')
        ->leftJoin('s.Etat e')
        ->andWhere('e.disponible = ?', true)
        ->andWhere('s.materiel_id = ?', $materiel_id)
        ->groupBy('s.id');
    return $q;
  }

}