<?php

/**
 * SubventionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubventionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubventionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subvention');
    }
}