<?php

/**
 * TransactionMoyenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TransactionMoyenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TransactionMoyenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TransactionMoyen');
    }
}