<?php

/**
 * TypeAssoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeAssoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeAssoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeAsso');
    }
}