<?php

/**
 * UserSemestreTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSemestreTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object UserSemestreTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('UserSemestre');
    }

    public function getAllByProfile($profile) {
        $q = $this->createQuery('q')
            ->where('q.user_id = ?', $profile);
        return $q;
    }
}