<?php

/**
 * UserSportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserSportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserSport');
    }
    
    public function getAllMySport($profile)
    {
      $q = $this->createQuery('q')
          ->where('q.user_id = ?',$profile);
      return $q;
    }
}