<?php

/**
 * UserSportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserSportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserSport');
    }
}