<?php

/**
 * UserUvTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserUvTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserUvTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserUv');
    }
}