<?php

/**
 * UVTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UVTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UVTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UV');
    }
}