<?php

/**
 * VoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vote');
    }

    public function getVoteForUserAndSemestre($user_id,$semestre_id) {
      $q = $this->createQuery('q')
                ->select('q.id')
                ->where('q.user_id = ? AND q.semestre_id = ?',array($user_id,$semestre_id))
                ->limit(1);
      return $q;
    }
}