<?php

/**
 * WeekmailArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WeekmailArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WeekmailArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WeekmailArticle');
    }
}