<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{

  /**
   * Returns an array containing all permissions, including groups permissions
   * and single permissions.
   *
   * @return array
   */
  public function getAllPermissions()
  {
    if(!$this->_allPermissions)
    {
      $this->_allPermissions = parent::getAllPermissions();
      foreach($this->getAssoMember() as $asso_member)
      {
        $this->_allPermissions[$asso_member->getAsso()->getNameSlug().'_'.$asso_member->getRole()->getNameSlug()] = $asso_member;
      }
    }
    
    return $this->_allPermissions;
  }
  
}
