<?php

/**
 * PluginGalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gallery');
    }
}