<?php

/**
 * PluginGalleryneFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGalleryneFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGalleryneFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGalleryneFile');
    }
}