<?php

/**
 * PluginPhotosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPhotosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPhotosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Photos');
    }
    public function getDefault($gallery_id) {
        return $this->createQuery('c')
                ->andWhere('c.gallery_id = ?', $gallery_id)
                ->andWhere('c.is_default = ?', 1)
                ->fetchOne();
    }
}