generator:
  class: sfDoctrineGenerator
  param:
    model_class:           VoteListe
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          vote_liste
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:
        display: [nom, description, membres, semestre_id, count]
      form:    ~
      edit:    ~
      new:     ~
