<?php

/**
 * GalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryTable extends PluginGalleryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gallery');
    }
}