<?php

/**
 * GalleryneFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryneFileTable extends PluginGalleryneFileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GalleryneFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GalleryneFile');
    }
}