<?php

/**
 * PhotosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotosTable extends PluginPhotosTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Photos');
    }
}