<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpole extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('pole', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'asso_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'couleur' => 
             array(
              'type' => 'string',
              'length' => 7,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('pole');
    }
}