<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addannonce extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('annonce', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'categorie_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'titre' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 250,
             ),
             'texte' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'offre' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 1,
              'length' => 25,
             ),
             'lieu' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'prix' => 
             array(
              'type' => 'float',
              'notnull' => true,
              'default' => 0,
              'length' => NULL,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('annonce');
    }
}