<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addplace extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('place', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'street' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'zipcode' => 
             array(
              'type' => 'string',
              'length' => 10,
             ),
             'city' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'country' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'phone' => 
             array(
              'type' => 'string',
              'length' => 15,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('place');
    }
}