<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('charte_info', 'charte_info_asso_id_asso_id', array(
             'name' => 'charte_info_asso_id_asso_id',
             'local' => 'asso_id',
             'foreign' => 'id',
             'foreignTable' => 'asso',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('charte_info', 'charte_info_responsable_id_sf_guard_user_id', array(
             'name' => 'charte_info_responsable_id_sf_guard_user_id',
             'local' => 'responsable_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->addIndex('charte_info', 'charte_info_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
        $this->addIndex('charte_info', 'charte_info_responsable_id', array(
             'fields' => 
             array(
              0 => 'responsable_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('charte_info', 'charte_info_asso_id_asso_id');
        $this->dropForeignKey('charte_info', 'charte_info_responsable_id_sf_guard_user_id');
        $this->removeIndex('charte_info', 'charte_info_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
        $this->removeIndex('charte_info', 'charte_info_responsable_id', array(
             'fields' => 
             array(
              0 => 'responsable_id',
             ),
             ));
    }
}