<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('asso', 'charte_info', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->changeColumn('asso', 'name', 'string', '50', array(
             'notnull' => '1',
             ));
        $this->changeColumn('asso', 'login', 'string', '32', array(
             'notnull' => '1',
             ));
        $this->changeColumn('asso', 'active', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '1',
             ));
        $this->changeColumn('asso', 'passation', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('asso', 'charte_info');
    }
}