<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('charte_info', 'charte_info_semestre_id_semestre_id', array(
             'name' => 'charte_info_semestre_id_semestre_id',
             'local' => 'semestre_id',
             'foreign' => 'id',
             'foreignTable' => 'semestre',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->addIndex('charte_info', 'charte_info_semestre_id', array(
             'fields' => 
             array(
              0 => 'semestre_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('charte_info', 'charte_info_semestre_id_semestre_id');
        $this->removeIndex('charte_info', 'charte_info_semestre_id', array(
             'fields' => 
             array(
              0 => 'semestre_id',
             ),
             ));
    }
}