<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('emprunt', 'emprunt_materiel_id_materiel_id', array(
             'name' => 'emprunt_materiel_id_materiel_id',
             'local' => 'materiel_id',
             'foreign' => 'id',
             'foreignTable' => 'materiel',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('emprunt', 'emprunt_user_id_sf_guard_user_id', array(
             'name' => 'emprunt_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('emprunt', 'emprunt_asso_id_asso_id', array(
             'name' => 'emprunt_asso_id_asso_id',
             'local' => 'asso_id',
             'foreign' => 'id',
             'foreignTable' => 'asso',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('materiel', 'materiel_asso_id_asso_id', array(
             'name' => 'materiel_asso_id_asso_id',
             'local' => 'asso_id',
             'foreign' => 'id',
             'foreignTable' => 'asso',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('stock', 'stock_materiel_id_materiel_id', array(
             'name' => 'stock_materiel_id_materiel_id',
             'local' => 'materiel_id',
             'foreign' => 'id',
             'foreignTable' => 'materiel',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('stock', 'stock_etat_id_etat_id', array(
             'name' => 'stock_etat_id_etat_id',
             'local' => 'etat_id',
             'foreign' => 'id',
             'foreignTable' => 'etat',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('emprunt', 'emprunt_materiel_id', array(
             'fields' => 
             array(
              0 => 'materiel_id',
             ),
             ));
        $this->addIndex('emprunt', 'emprunt_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('emprunt', 'emprunt_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
        $this->addIndex('materiel', 'materiel_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
        $this->addIndex('stock', 'stock_materiel_id', array(
             'fields' => 
             array(
              0 => 'materiel_id',
             ),
             ));
        $this->addIndex('stock', 'stock_etat_id', array(
             'fields' => 
             array(
              0 => 'etat_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('emprunt', 'emprunt_materiel_id_materiel_id');
        $this->dropForeignKey('emprunt', 'emprunt_user_id_sf_guard_user_id');
        $this->dropForeignKey('emprunt', 'emprunt_asso_id_asso_id');
        $this->dropForeignKey('materiel', 'materiel_asso_id_asso_id');
        $this->dropForeignKey('stock', 'stock_materiel_id_materiel_id');
        $this->dropForeignKey('stock', 'stock_etat_id_etat_id');
        $this->removeIndex('emprunt', 'emprunt_materiel_id', array(
             'fields' => 
             array(
              0 => 'materiel_id',
             ),
             ));
        $this->removeIndex('emprunt', 'emprunt_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('emprunt', 'emprunt_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
        $this->removeIndex('materiel', 'materiel_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
        $this->removeIndex('stock', 'stock_materiel_id', array(
             'fields' => 
             array(
              0 => 'materiel_id',
             ),
             ));
        $this->removeIndex('stock', 'stock_etat_id', array(
             'fields' => 
             array(
              0 => 'etat_id',
             ),
             ));
    }
}