<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('asso', 'url_site');
        $this->removeColumn('event_type', 'color');
    }

    public function down()
    {
        $this->addColumn('asso', 'url_site', 'string', '100', array(
             ));
        $this->addColumn('event_type', 'color', 'string', '7', array(
             ));
    }
}