<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('stock', 'etat_id', 'integer', '8', array(
             'notnull' => '1',
             'default' => '1',
             ));
    }

    public function down()
    {

    }
}