<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('services', 'services_type_id_event_type_id', array(
             'name' => 'services_type_id_event_type_id',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'event_type',
             ));
        $this->addIndex('services', 'services_type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('services', 'services_type_id_event_type_id');
        $this->removeIndex('services', 'services_type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
    }
}