<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('charte_info', 'ip', 'string', '15', array(
             'notnull' => '1',
             ));
        $this->addColumn('charte_info', 'asso', 'string', '20', array(
             'notnull' => '1',
             ));
        $this->addColumn('charte_info', 'login', 'string', '20', array(
             'notnull' => '1',
             ));
        $this->changeColumn('charte_info', 'date', 'timestamp', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->changeColumn('charte_info', 'timestamp', 'date', '', array(
             'notnull' => '1',
             ));
        $this->removeColumn('charte_info', 'ip');
        $this->removeColumn('charte_info', 'asso');
        $this->removeColumn('charte_info', 'login');
    }
}