<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('vote', 'vote_semestre_id_semestre_id', array(
             'name' => 'vote_semestre_id_semestre_id',
             'local' => 'semestre_id',
             'foreign' => 'id',
             'foreignTable' => 'semestre',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('vote', 'vote_user_id_sf_guard_user_id', array(
             'name' => 'vote_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('vote_liste', 'vote_liste_semestre_id_semestre_id', array(
             'name' => 'vote_liste_semestre_id_semestre_id',
             'local' => 'semestre_id',
             'foreign' => 'id',
             'foreignTable' => 'semestre',
             ));
        $this->addIndex('vote', 'vote_semestre_id', array(
             'fields' => 
             array(
              0 => 'semestre_id',
             ),
             ));
        $this->addIndex('vote', 'vote_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('vote_liste', 'vote_liste_semestre_id', array(
             'fields' => 
             array(
              0 => 'semestre_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('vote', 'vote_semestre_id_semestre_id');
        $this->dropForeignKey('vote', 'vote_user_id_sf_guard_user_id');
        $this->dropForeignKey('vote_liste', 'vote_liste_semestre_id_semestre_id');
        $this->removeIndex('vote', 'vote_semestre_id', array(
             'fields' => 
             array(
              0 => 'semestre_id',
             ),
             ));
        $this->removeIndex('vote', 'vote_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('vote_liste', 'vote_liste_semestre_id', array(
             'fields' => 
             array(
              0 => 'semestre_id',
             ),
             ));
    }
}