<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('budget', 'budget_semestre_id_semestre_id', array(
             'name' => 'budget_semestre_id_semestre_id',
             'local' => 'semestre_id',
             'foreign' => 'id',
             'foreignTable' => 'semestre',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('budget', 'budget_budget_id_budget_id', array(
             'name' => 'budget_budget_id_budget_id',
             'local' => 'budget_id',
             'foreign' => 'id',
             'foreignTable' => 'budget',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('budget', 'budget_budget_categorie_id_budget_categorie_id', array(
             'name' => 'budget_budget_categorie_id_budget_categorie_id',
             'local' => 'budget_categorie_id',
             'foreign' => 'id',
             'foreignTable' => 'budget_categorie',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('budget_categorie', 'budget_categorie_asso_id_asso_id', array(
             'name' => 'budget_categorie_asso_id_asso_id',
             'local' => 'asso_id',
             'foreign' => 'id',
             'foreignTable' => 'asso',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->addIndex('budget', 'budget_semestre_id', array(
             'fields' => 
             array(
              0 => 'semestre_id',
             ),
             ));
        $this->addIndex('budget', 'budget_budget_id', array(
             'fields' => 
             array(
              0 => 'budget_id',
             ),
             ));
        $this->addIndex('budget', 'budget_budget_categorie_id', array(
             'fields' => 
             array(
              0 => 'budget_categorie_id',
             ),
             ));
        $this->addIndex('budget_categorie', 'budget_categorie_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('budget', 'budget_semestre_id_semestre_id');
        $this->dropForeignKey('budget', 'budget_budget_id_budget_id');
        $this->dropForeignKey('budget', 'budget_budget_categorie_id_budget_categorie_id');
        $this->dropForeignKey('budget_categorie', 'budget_categorie_asso_id_asso_id');
        $this->removeIndex('budget', 'budget_semestre_id', array(
             'fields' => 
             array(
              0 => 'semestre_id',
             ),
             ));
        $this->removeIndex('budget', 'budget_budget_id', array(
             'fields' => 
             array(
              0 => 'budget_id',
             ),
             ));
        $this->removeIndex('budget', 'budget_budget_categorie_id', array(
             'fields' => 
             array(
              0 => 'budget_categorie_id',
             ),
             ));
        $this->removeIndex('budget_categorie', 'budget_categorie_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
    }
}