<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('budget_moyen');
        $this->createTable('avance_treso', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'asso_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'commentaire' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'transaction_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('budget_poste', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'asso_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'budget_categorie_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'nombre' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '1',
              'length' => '8',
             ),
             'prix_unitaire' => 
             array(
              'type' => 'decimal',
              'scale' => '4',
              'notnull' => '1',
              'default' => '0',
              'length' => '8',
             ),
             'commentaire' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'budget_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('compte_banquaire', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'asso_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'banque' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'num_compte' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('note_de_frais', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'asso_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'transaction_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('subvention', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'asso_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'montant' => 
             array(
              'type' => 'decimal',
              'scale' => '4',
              'notnull' => '1',
              'length' => '8',
             ),
             'commentaire' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('transaction', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'asso_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'compte_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'libelle' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'montant' => 
             array(
              'type' => 'decimal',
              'scale' => '4',
              'notnull' => '1',
              'default' => '0',
              'length' => '8',
             ),
             'commentaire' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'date_transaction' => 
             array(
              'type' => 'date',
              'notnull' => '1',
              'length' => '25',
             ),
             'date_rapprochement' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'budget_poste_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'moyen_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'moyen_commentaire' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'note_de_frais_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('transaction_moyen', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'detail' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('budget', 'budget_categorie_id');
        $this->removeColumn('budget', 'nombre');
        $this->removeColumn('budget', 'prix_unitaire');
        $this->removeColumn('budget', 'commentaire');
        $this->removeColumn('budget', 'date_trx');
        $this->removeColumn('budget', 'budget_id');
        $this->removeColumn('budget', 'moyen_id');
        $this->removeColumn('budget', 'moyen_commentaire');
        $this->addColumn('budget', 'asso_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('budget_categorie', 'commentaire', 'string', '', array(
             'notnull' => '1',
             ));
        $this->addColumn('budget_categorie', 'deleted_at', 'timestamp', '25', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->createTable('budget_moyen', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->dropTable('avance_treso');
        $this->dropTable('budget_poste');
        $this->dropTable('compte_banquaire');
        $this->dropTable('note_de_frais');
        $this->dropTable('subvention');
        $this->dropTable('transaction');
        $this->dropTable('transaction_moyen');
        $this->addColumn('budget', 'budget_categorie_id', 'integer', '8', array(
             'notnull' => '',
             ));
        $this->addColumn('budget', 'nombre', 'integer', '8', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('budget', 'prix_unitaire', 'integer', '8', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('budget', 'commentaire', 'string', '', array(
             'notnull' => '',
             ));
        $this->addColumn('budget', 'date_trx', 'date', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('budget', 'budget_id', 'integer', '8', array(
             'notnull' => '',
             ));
        $this->addColumn('budget', 'moyen_id', 'integer', '8', array(
             'notnull' => '',
             ));
        $this->addColumn('budget', 'moyen_commentaire', 'string', '', array(
             'notnull' => '',
             ));
        $this->removeColumn('budget', 'asso_id');
        $this->removeColumn('budget_categorie', 'commentaire');
        $this->removeColumn('budget_categorie', 'deleted_at');
    }
}