<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version27 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('budget', 'budget_asso_id_asso_id', array(
             'name' => 'budget_asso_id_asso_id',
             'local' => 'asso_id',
             'foreign' => 'id',
             'foreignTable' => 'asso',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->addIndex('budget', 'budget_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('budget', 'budget_asso_id_asso_id');
        $this->removeIndex('budget', 'budget_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
    }
}