<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version33 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('budget_categorie', 'type', 'enum', '', array(
             'values' => 
             array(
              0 => 'depenses',
              1 => 'recettes',
             ),
             ));
    }

    public function down()
    {
        $this->removeColumn('budget_categorie', 'type');
    }
}