<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version31 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('avance_treso', 'commentaire', 'string', '', array(
             'notnull' => '',
             ));
        $this->changeColumn('budget_poste', 'commentaire', 'string', '', array(
             'notnull' => '',
             ));
        $this->changeColumn('subvention', 'commentaire', 'string', '', array(
             'notnull' => '',
             ));
        $this->changeColumn('transaction', 'commentaire', 'string', '', array(
             'notnull' => '',
             ));
        $this->changeColumn('transaction', 'moyen_commentaire', 'string', '', array(
             'notnull' => '',
             ));
        $this->changeColumn('transaction_moyen', 'detail', 'string', '255', array(
             'notnull' => '',
             ));
    }

    public function down()
    {

    }
}