<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('budget_categorie', 'commentaire', 'string', '', array(
             'notnull' => '',
             ));
    }

    public function down()
    {

    }
}