<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version37 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('document', 'document_asso_id_asso_id', array(
             'name' => 'document_asso_id_asso_id',
             'local' => 'asso_id',
             'foreign' => 'id',
             'foreignTable' => 'asso',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->addIndex('document', 'document_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('document', 'document_asso_id_asso_id');
        $this->removeIndex('document', 'document_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
    }
}