<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addbudgetposte extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('budget_poste', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'asso_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'budget_categorie_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'nombre' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'default' => 1,
              'length' => 8,
             ),
             'prix_unitaire' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'notnull' => true,
              'default' => 0,
              'length' => 8,
             ),
             'commentaire' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => NULL,
             ),
             'budget_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('budget_poste');
    }
}