<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtransactionmoyen extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('transaction_moyen', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'detail' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('transaction_moyen');
    }
}