<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtransaction extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('transaction', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'asso_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'compte_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'libelle' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'montant' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'notnull' => true,
              'default' => 0,
              'length' => 8,
             ),
             'commentaire' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => NULL,
             ),
             'date_transaction' => 
             array(
              'type' => 'date',
              'notnull' => true,
              'length' => 25,
             ),
             'date_rapprochement' => 
             array(
              'type' => 'date',
              'notnull' => false,
              'length' => 25,
             ),
             'budget_poste_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'moyen_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'moyen_commentaire' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => NULL,
             ),
             'note_de_frais_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('transaction');
    }
}