<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addweekmailarticle extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('weekmail_article', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'asso_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 200,
             ),
             'text' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'image' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'summary' => 
             array(
              'type' => 'string',
              'length' => 150,
             ),
             'weekmail_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'article_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('weekmail_article');
    }
}