<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addFkAvanceTreso extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('avance_treso', 'avance_treso_emetteur_id_asso_id', array(
             'name' => 'avance_treso_emetteur_id_asso_id',
             'local' => 'emetteur_id',
             'foreign' => 'id',
             'foreignTable' => 'asso',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('avance_treso', 'avance_treso_asso_id_asso_id', array(
             'name' => 'avance_treso_asso_id_asso_id',
             'local' => 'asso_id',
             'foreign' => 'id',
             'foreignTable' => 'asso',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('avance_treso', 'avance_treso_transaction_id_transaction_id', array(
             'name' => 'avance_treso_transaction_id_transaction_id',
             'local' => 'transaction_id',
             'foreign' => 'id',
             'foreignTable' => 'transaction',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('avance_treso', 'avance_treso_transaction_emetteur_id_transaction_id', array(
             'name' => 'avance_treso_transaction_emetteur_id_transaction_id',
             'local' => 'transaction_emetteur_id',
             'foreign' => 'id',
             'foreignTable' => 'transaction',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->addIndex('avance_treso', 'avance_treso_emetteur_id', array(
             'fields' => 
             array(
              0 => 'emetteur_id',
             ),
             ));
        $this->addIndex('avance_treso', 'avance_treso_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
        $this->addIndex('avance_treso', 'avance_treso_transaction_id', array(
             'fields' => 
             array(
              0 => 'transaction_id',
             ),
             ));
        $this->addIndex('avance_treso', 'avance_treso_transaction_emetteur_id', array(
             'fields' => 
             array(
              0 => 'transaction_emetteur_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('avance_treso', 'avance_treso_emetteur_id_asso_id');
        $this->dropForeignKey('avance_treso', 'avance_treso_asso_id_asso_id');
        $this->dropForeignKey('avance_treso', 'avance_treso_transaction_id_transaction_id');
        $this->dropForeignKey('avance_treso', 'avance_treso_transaction_emetteur_id_transaction_id');
        $this->removeIndex('avance_treso', 'avance_treso_emetteur_id', array(
             'fields' => 
             array(
              0 => 'emetteur_id',
             ),
             ));
        $this->removeIndex('avance_treso', 'avance_treso_asso_id', array(
             'fields' => 
             array(
              0 => 'asso_id',
             ),
             ));
        $this->removeIndex('avance_treso', 'avance_treso_transaction_id', array(
             'fields' => 
             array(
              0 => 'transaction_id',
             ),
             ));
        $this->removeIndex('avance_treso', 'avance_treso_transaction_emetteur_id', array(
             'fields' => 
             array(
              0 => 'transaction_emetteur_id',
             ),
             ));
    }
}
