<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version50 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('charte_info', 'date', 'timestamp', '25', array(
             'notnull' => '1',
             ));
        $this->changeColumn('document', 'type_id', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}