<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version51 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('avance_treso', 'emetteur_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('avance_treso', 'transaction_emetteur_id', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('avance_treso', 'emetteur_id');
        $this->removeColumn('avance_treso', 'transaction_emetteur_id');
    }
}