<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version54 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('budget_poste', 'prix_unitaire', 'decimal', '8', array(
             'scale' => '2',
             'notnull' => '1',
             'default' => '0',
             ));
        $this->changeColumn('subvention', 'montant', 'decimal', '8', array(
             'scale' => '2',
             'notnull' => '1',
             ));
        $this->changeColumn('transaction', 'montant', 'decimal', '8', array(
             'scale' => '2',
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {

    }
}