<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addgallery extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('gallery', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'private' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'comment' => 'True means that this gallery has been added by the widget',
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'gallery_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('gallery');
    }
}