<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addservice extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('service', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'resume' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 150,
             ),
             'logo' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'type_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('service');
    }
}