<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addphotos extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('photos', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'filename' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'size' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'is_default' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'order_photo' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'gallery_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'photos_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('photos');
    }
}