<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addusersemestre extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user_semestre', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'branche_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'num' => 
             array(
              'type' => 'string',
              'length' => 4,
             ),
             'abroad' => 
             array(
              'type' => 'string',
              'length' => 30,
             ),
             'semestre_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('user_semestre');
    }
}