<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version54 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('charte_locaux', 'motif', 'text', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('charte_locaux', 'motif');
    }
}