<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version74 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('info_job_categorie', 'description');
    }

    public function down()
    {
        $this->addColumn('info_job_categorie', 'description', 'string', '255', array(
             'notnull' => '1',
             ));
    }
}