<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version77 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('carnet_avantages', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'nom' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'adresse' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'tel' => 
             array(
              'type' => 'string',
              'length' => '15',
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->changeColumn('partenaire', 'nom', 'string', '100', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('carnet_avantages');
    }
}