<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addgalleriephotofk_v2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('photo', 'photo_author_sf_guard_user_id', array(
             'name' => 'photo_author_sf_guard_user_id',
             'local' => 'author',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('photo', 'photo_author', array(
             'fields' => 
             array(
              0 => 'author',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('photo', 'photo_author_sf_guard_user_id');
        $this->removeIndex('photo', 'photo_author', array(
             'fields' => 
             array(
              0 => 'author',
             ),
             ));
    }
}