<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addgalleriephoto_v2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('photo', 'image', 'string', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}