<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddGuestAsso extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('event_guest_asso', array(
             'event_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'asso_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'event_id',
              1 => 'asso_id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('event_guest_asso');
    }
}