<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addSalleTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('reservation', 'reservation_id_user_reserve_sf_guard_user_id', array(
             'name' => 'reservation_id_user_reserve_sf_guard_user_id',
             'local' => 'id_user_reserve',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('reservation', 'reservation_id_user_valid_sf_guard_user_id', array(
             'name' => 'reservation_id_user_valid_sf_guard_user_id',
             'local' => 'id_user_valid',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('reservation', 'reservation_id_asso_asso_id', array(
             'name' => 'reservation_id_asso_asso_id',
             'local' => 'id_asso',
             'foreign' => 'id',
             'foreignTable' => 'asso',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('reservation', 'reservation_id_salle_salle_id', array(
             'name' => 'reservation_id_salle_salle_id',
             'local' => 'id_salle',
             'foreign' => 'id',
             'foreignTable' => 'salle',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->createForeignKey('salle', 'salle_id_pole_pole_id', array(
             'name' => 'salle_id_pole_pole_id',
             'local' => 'id_pole',
             'foreign' => 'id',
             'foreignTable' => 'pole',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->addIndex('reservation', 'reservation_id_user_reserve', array(
             'fields' => 
             array(
              0 => 'id_user_reserve',
             ),
             ));
        $this->addIndex('reservation', 'reservation_id_user_valid', array(
             'fields' => 
             array(
              0 => 'id_user_valid',
             ),
             ));
        $this->addIndex('reservation', 'reservation_id_asso', array(
             'fields' => 
             array(
              0 => 'id_asso',
             ),
             ));
        $this->addIndex('reservation', 'reservation_id_salle', array(
             'fields' => 
             array(
              0 => 'id_salle',
             ),
             ));
        $this->addIndex('salle', 'salle_id_pole', array(
             'fields' => 
             array(
              0 => 'id_pole',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('reservation', 'reservation_id_user_reserve_sf_guard_user_id');
        $this->dropForeignKey('reservation', 'reservation_id_user_valid_sf_guard_user_id');
        $this->dropForeignKey('reservation', 'reservation_id_asso_asso_id');
        $this->dropForeignKey('reservation', 'reservation_id_salle_salle_id');
        $this->dropForeignKey('salle', 'salle_id_pole_pole_id');
        $this->removeIndex('reservation', 'reservation_id_user_reserve', array(
             'fields' => 
             array(
              0 => 'id_user_reserve',
             ),
             ));
        $this->removeIndex('reservation', 'reservation_id_user_valid', array(
             'fields' => 
             array(
              0 => 'id_user_valid',
             ),
             ));
        $this->removeIndex('reservation', 'reservation_id_asso', array(
             'fields' => 
             array(
              0 => 'id_asso',
             ),
             ));
        $this->removeIndex('reservation', 'reservation_id_salle', array(
             'fields' => 
             array(
              0 => 'id_salle',
             ),
             ));
        $this->removeIndex('salle', 'salle_id_pole', array(
             'fields' => 
             array(
              0 => 'id_pole',
             ),
             ));
    }
}
