<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UpdateLeSaviezVous extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('weekmail', 'le_saviez_vous', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('weekmail', 'le_saviez_vous');
    }
}
