<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addCharteLocauxTypeFk extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('charte_locaux', 'charte_locaux_type_id_charte_locaux_type_id', array(
             'name' => 'charte_locaux_type_id_charte_locaux_type_id',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'charte_locaux_type',
             'onUpdate' => 'CASCADE',
             'onDelete' => '',
             ));
        $this->addIndex('charte_locaux', 'charte_locaux_type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('charte_locaux', 'charte_locaux_type_id_charte_locaux_type_id');
        $this->removeIndex('charte_locaux', 'charte_locaux_type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
    }
}