<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addCharteLocauxType extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('charte_locaux_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '200',
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('charte_locaux', 'porte_mde');
        $this->removeColumn('charte_locaux', 'bat_a');
        $this->removeColumn('charte_locaux', 'locaux_pic');
        $this->removeColumn('charte_locaux', 'mde_complete');
        $this->removeColumn('charte_locaux', 'bureau_polar');
        $this->removeColumn('charte_locaux', 'perm_polar');
        $this->removeColumn('charte_locaux', 'salles_musique');
        $this->addColumn('charte_locaux', 'type_id', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('charte_locaux_type', 'correspondance', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('charte_locaux_type');
        $this->addColumn('charte_locaux', 'porte_mde', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('charte_locaux', 'bat_a', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('charte_locaux', 'locaux_pic', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('charte_locaux', 'mde_complete', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('charte_locaux', 'bureau_polar', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('charte_locaux', 'perm_polar', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('charte_locaux', 'salles_musique', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->removeColumn('charte_locaux', 'type_id');
    }
}