<?php

/**
 * BaseGalleryneFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $filename
 * @property string $size
 * @property integer $position
 * @property boolean $is_default
 * 
 * @method string        getTitle()       Returns the current record's "title" value
 * @method string        getDescription() Returns the current record's "description" value
 * @method string        getFilename()    Returns the current record's "filename" value
 * @method string        getSize()        Returns the current record's "size" value
 * @method integer       getPosition()    Returns the current record's "position" value
 * @method boolean       getIsDefault()   Returns the current record's "is_default" value
 * @method GalleryneFile setTitle()       Sets the current record's "title" value
 * @method GalleryneFile setDescription() Sets the current record's "description" value
 * @method GalleryneFile setFilename()    Sets the current record's "filename" value
 * @method GalleryneFile setSize()        Sets the current record's "size" value
 * @method GalleryneFile setPosition()    Sets the current record's "position" value
 * @method GalleryneFile setIsDefault()   Sets the current record's "is_default" value
 * 
 * @package    simde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGalleryneFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('galleryne_file');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('size', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('is_default', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}